# Generated by Django 5.2.1 on 2026-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code camion')),
                ('immatriculation', models.CharField(max_length=30, unique=True, verbose_name='Immatriculation')),
                ('marque_modele', models.CharField(max_length=120, verbose_name='Marque / Modèle')),
                ('capacite_tonnes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacité (T)')),
                ('date_acquisition', models.DateField(verbose_name="Date d'acquisition")),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Prix d'achat (GNF)")),
                ('duree_amortissement', models.PositiveIntegerField(default=5, verbose_name='Durée amortissement (années)')),
                ('statut', models.CharField(choices=[('SERVICE', 'En service'), ('ATELIER', 'En atelier'), ('HS', 'Hors service'), ('VENDU', 'Vendu')], default='SERVICE', max_length=10)),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camions',
                'ordering': ['code'],
            },
        ),
    ]
