# Generated by Django 5.2.1 on 2026-04-17 10:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='N° contrat')),
                ('client', models.CharField(max_length=120, verbose_name='Client (société minière)')),
                ('type_facturation', models.CharField(choices=[('TONNE', 'À la tonne'), ('TONNE_KM', 'Tonne × km'), ('VOYAGE', 'Au voyage'), ('FORFAIT', 'Forfait mensuel')], default='TONNE', max_length=10, verbose_name='Type de facturation')),
                ('tarif', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tarif unitaire')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Contrat client',
                'verbose_name_plural': 'Contrats clients',
                'ordering': ['-actif', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('numero', models.CharField(max_length=40, unique=True, verbose_name='N° facture')),
                ('periode_mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('periode_annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('nb_bons', models.PositiveIntegerField(default=0, verbose_name='Nombre de bons')),
                ('nb_rotations', models.PositiveIntegerField(default=0, verbose_name='Nombre de rotations')),
                ('tonnage_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tonnage total (T)')),
                ('distance_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Distance totale (km)')),
                ('montant_brut', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant brut (GNF)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bonus (GNF)')),
                ('penalites', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pénalités (GNF)')),
                ('deduction_carburant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Déduction avance carburant (GNF)')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant HT (GNF)')),
                ('taux_tva', models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5, verbose_name='Taux TVA')),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='TVA (GNF)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant TTC (GNF)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='facturation.contrat')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
