# Generated by Django 4.2.7 on 2026-04-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0134_alter_bulletinpaie_contribution_onfpp_and_more"),
        ("paie", "0134_seuil_ta_onfpp_30"),
    ]

    operations = []
