# Generated by Django 4.2.29 on 2026-05-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0137_align_onfpp_base_vf_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrescalculpaie',
            name='mode_base_vf',
            field=models.CharField(choices=[('brut_moins_deduction', 'Mode optimise GuineeRH : brut - deduction CGI plafonnee'), ('brut', 'Mode strict fiscal : VF/ONFPP sur salaire brut'), ('formule', 'Formule personnalisee')], default='brut_moins_deduction', max_length=30),
        ),
    ]
