# Generated by Django 4.2.29 on 2026-05-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0138_alter_parametrescalculpaie_mode_base_vf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrescalculpaie',
            name='mode_base_vf',
            field=models.CharField(choices=[('brut_moins_deduction', 'Mode optimise GuineeRH : VF/TA sur brut - deduction CGI plafonnee'), ('brut', 'Mode strict fiscal : VF/TA sur salaire brut'), ('formule', 'Formule personnalisee')], default='brut_moins_deduction', max_length=30),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='base_onfpp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base de calcul ONFPP', max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrescalculpaie',
            name='mode_base_onfpp',
            field=models.CharField(choices=[('base_vf', 'Mode standard GuineeRH : ONFPP sur base VF/TA'), ('brut', 'Mode strict fiscal : ONFPP sur salaire brut')], default='base_vf', max_length=20),
        ),
    ]
