# Generated by Django 4.2.29 on 2026-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0139_bulletinpaie_base_onfpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationpaieentreprise',
            name='jours_conges_par_mois',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Minimum légal Code du Travail Art. 222 : 2,5 j/mois (30 j/an). Une convention collective peut être plus favorable.', max_digits=4, verbose_name='Jours de congé acquis par mois'),
        ),
    ]
