# Generated by Django 5.2.11 on 2026-06-16 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_alter_entreprise_type_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_articles', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'stock_categorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('actif', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_stock', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'stock_fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence / Code')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('litre', 'Litre'), ('metre', 'Mètre'), ('carton', 'Carton'), ('paquet', 'Paquet'), ('sac', 'Sac'), ('lot', 'Lot'), ('autre', 'Autre')], default='piece', max_length=10, verbose_name='Unité de mesure')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Prix d'achat (GNF)")),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix de vente (GNF)')),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Seuil d'alerte")),
                ('emplacement', models.CharField(blank=True, max_length=120, verbose_name='Emplacement / Magasin')),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.entreprise')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stock.categoriearticle', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stock.fournisseur', verbose_name='Fournisseur principal')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'stock_article',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('date_inventaire', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'inventaire")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_cours', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires_stock', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'db_table': 'stock_inventaire',
                'ordering': ['-date_inventaire', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock théorique')),
                ('quantite_physique', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock physique compté')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Écart')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='stock.article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'db_table': 'stock_ligne_inventaire',
                'ordering': ['article__designation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], default='entree', max_length=12, verbose_name='Type de mouvement')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité')),
                ('quantite_avant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock avant')),
                ('quantite_apres', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock après')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire (GNF)')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif / Justification')),
                ('reference_document', models.CharField(blank=True, max_length=80, verbose_name='Réf. document (BL, facture...)')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.article')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='core.entreprise')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stock.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'stock_mouvement',
                'ordering': ['-date_mouvement', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriearticle',
            constraint=models.UniqueConstraint(fields=('entreprise', 'nom'), name='unique_categorie_nom_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('entreprise', 'reference'), name='unique_article_reference_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='inventaire',
            constraint=models.UniqueConstraint(fields=('entreprise', 'reference'), name='unique_inventaire_reference_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='ligneinventaire',
            constraint=models.UniqueConstraint(fields=('inventaire', 'article'), name='unique_article_par_inventaire'),
        ),
    ]
