# Generated by Django 5.2.11 on 2026-06-16 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entreprise_type_module_stock'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_barres',
            field=models.CharField(blank=True, max_length=80, verbose_name='Code-barres / QR'),
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stock/articles/', verbose_name='Photo du produit'),
        ),
        migrations.AddField(
            model_name='article',
            name='stock_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock maximum (0 = illimité)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='emplacement',
            field=models.CharField(blank=True, max_length=120, verbose_name='Emplacement / Rayon / Étagère'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité en stock (tous dépôts)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock minimum (alerte)'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('transfert', 'Transfert')], default='entree', max_length=12, verbose_name='Type de mouvement'),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du dépôt')),
                ('type_depot', models.CharField(choices=[('principal', 'Magasin principal'), ('secondaire', 'Dépôt secondaire'), ('vehicule', 'Véhicule (stock mobile)'), ('boutique', 'Boutique / Point de vente'), ('chantier', 'Chantier'), ('autre', 'Autre')], default='principal', max_length=12, verbose_name='Type de dépôt')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse / Localisation')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Dépôt par défaut')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'db_table': 'stock_depot',
                'ordering': ['-par_defaut', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='inventaire',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to='stock.depot', verbose_name='Dépôt inventorié'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stock.depot', verbose_name='Dépôt'),
        ),
        migrations.CreateModel(
            name='StockArticleDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_depots', to='stock.article')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_articles', to='stock.depot')),
            ],
            options={
                'verbose_name': 'Stock par dépôt',
                'verbose_name_plural': 'Stocks par dépôt',
                'db_table': 'stock_article_depot',
                'ordering': ['depot__nom'],
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du transfert')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='stock.article')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('depot_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='stock.depot', verbose_name='Dépôt destination')),
                ('depot_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='stock.depot', verbose_name='Dépôt source')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'db_table': 'stock_transfert',
                'ordering': ['-date_transfert', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='depot',
            constraint=models.UniqueConstraint(fields=('entreprise', 'nom'), name='unique_depot_nom_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='stockarticledepot',
            constraint=models.UniqueConstraint(fields=('article', 'depot'), name='unique_article_par_depot'),
        ),
    ]
