# Generated by Django 5.2.11 on 2026-06-16 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entreprise_type_module_stock'),
        ('stock', '0003_depot_par_defaut_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='delai_livraison_jours',
            field=models.PositiveIntegerField(default=0, verbose_name='Délai moyen de livraison (jours)'),
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('date_commande', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Livraison prévue le')),
                ('statut', models.CharField(choices=[('brouillon', "Demande d'achat"), ('validee', 'Bon de commande validé'), ('partiellement_recue', 'Partiellement reçue'), ('recue', 'Réception complète'), ('annulee', 'Annulée')], default='brouillon', max_length=22)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_recues', to='stock.depot', verbose_name='Dépôt de réception')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_fournisseur', to='core.entreprise')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='stock.fournisseur')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseur',
                'db_table': 'stock_commande_fournisseur',
                'ordering': ['-date_commande', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, verbose_name='N° de facture fournisseur')),
                ('date_facture', models.DateField(default=django.utils.timezone.now, verbose_name='Date de facture')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant HT (GNF)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant payé (GNF)')),
                ('statut', models.CharField(choices=[('impayee', 'Impayée'), ('partielle', 'Partiellement payée'), ('payee', 'Payée')], default='impayee', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='stock.commandefournisseur', verbose_name='Commande liée')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_fournisseur_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_fournisseur', to='core.entreprise')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseur',
                'db_table': 'stock_facture_fournisseur',
                'ordering': ['-date_facture', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité commandée')),
                ('quantite_recue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité reçue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire (GNF)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='stock.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.commandefournisseur')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'stock_ligne_commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant (GNF)')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=15, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Référence')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseur_crees', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='stock.facturefournisseur')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseur',
                'db_table': 'stock_paiement_fournisseur',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('date_reception', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception')),
                ('notes', models.TextField(blank=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='stock.commandefournisseur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_creees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='stock.depot', verbose_name='Dépôt')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions_fournisseur', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'db_table': 'stock_reception',
                'ordering': ['-date_reception', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité reçue')),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='stock.lignecommande')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.reception')),
            ],
            options={
                'verbose_name': 'Ligne de réception',
                'verbose_name_plural': 'Lignes de réception',
                'db_table': 'stock_ligne_reception',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='commandefournisseur',
            constraint=models.UniqueConstraint(fields=('entreprise', 'reference'), name='unique_commande_reference_par_entreprise'),
        ),
    ]
