# Generated by Django 5.2.11 on 2026-06-16 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entreprise_type_module_stock'),
        ('stock', '0004_fournisseur_delai_livraison_jours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=12, verbose_name='Type')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('remise_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise habituelle (%)')),
                ('actif', models.BooleanField(default=True)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'stock_client',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('devis', 'Devis'), ('proforma', 'Facture proforma'), ('facture', 'Facture')], default='devis', max_length=10, verbose_name='Type')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('date_document', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='Validité / Échéance')),
                ('remise_globale_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise globale (%)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='Taux TVA (%)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('converti', 'Converti en facture'), ('emise', 'Émise'), ('partielle', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Montant encaissé (GNF)')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='stock.client')),
                ('converti_depuis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='stock.documentvente', verbose_name='Converti depuis')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_vente_crees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_vente', to='stock.depot', verbose_name='Dépôt de livraison')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_vente', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Document de vente',
                'verbose_name_plural': 'Documents de vente',
                'db_table': 'stock_document_vente',
                'ordering': ['-date_document', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('date_livraison', models.DateField(default=django.utils.timezone.now, verbose_name='Date de livraison')),
                ('adresse_livraison', models.CharField(blank=True, max_length=255, verbose_name='Adresse de livraison')),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_creees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='stock.depot', verbose_name='Dépôt')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_livraison', to='core.entreprise')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='stock.documentvente')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'db_table': 'stock_bon_livraison',
                'ordering': ['-date_livraison', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire (GNF)')),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('quantite_livree', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité livrée')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='stock.article')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.documentvente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'db_table': 'stock_ligne_vente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité livrée')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.bonlivraison')),
                ('ligne_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='stock.lignevente')),
            ],
            options={
                'verbose_name': 'Ligne de livraison',
                'verbose_name_plural': 'Lignes de livraison',
                'db_table': 'stock_ligne_livraison',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Montant (GNF)')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money'), ('autre', 'Autre')], default='especes', max_length=15, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Référence du reçu')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_client_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='stock.documentvente')),
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': 'Paiements client',
                'db_table': 'stock_paiement_client',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrixSpecialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix spécial (GNF)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_speciaux', to='stock.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_speciaux', to='stock.client')),
            ],
            options={
                'verbose_name': 'Prix spécial client',
                'verbose_name_plural': 'Prix spéciaux client',
                'db_table': 'stock_prix_special_client',
                'ordering': ['article__designation'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentvente',
            constraint=models.UniqueConstraint(fields=('entreprise', 'reference'), name='unique_vente_reference_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='prixspecialclient',
            constraint=models.UniqueConstraint(fields=('client', 'article'), name='unique_prix_special_client_article'),
        ),
    ]
