# Generated by Django 5.2.11 on 2026-06-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entreprise_type_module_stock'),
        ('stock', '0005_client_documentvente_bonlivraison_lignevente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('directeur', 'Directeur'), ('magasinier', 'Magasinier'), ('responsable_achat', 'Responsable achat'), ('comptable', 'Comptable'), ('auditeur', 'Auditeur (lecture seule)')], default='administrateur', max_length=20)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle Stock',
                'verbose_name_plural': 'Rôles Stock',
                'db_table': 'stock_profil',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=15)),
                ('objet_type', models.CharField(max_length=60, verbose_name="Type d'objet")),
                ('objet_id', models.CharField(blank=True, max_length=40)),
                ('objet_libelle', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaux_stock', to='core.entreprise')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'stock_journal_audit',
                'ordering': ['-date_heure', '-id'],
                'indexes': [models.Index(fields=['entreprise', '-date_heure'], name='stock_journ_entrepr_29ba29_idx')],
            },
        ),
    ]
