# Generated by Django 5.2.11 on 2026-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_profilstock_journalaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cmup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût moyen pondéré (CMUP)'),
        ),
    ]
