# Generated by Django 5.2.11 on 2026-06-17 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entreprise_type_module_stock'),
        ('stock', '0008_init_cmup'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gestion_lot',
            field=models.BooleanField(default=False, verbose_name='Suivi par lot'),
        ),
        migrations.AddField(
            model_name='article',
            name='gestion_serie',
            field=models.BooleanField(default=False, verbose_name='Suivi par numéro de série'),
        ),
        migrations.AddField(
            model_name='article',
            name='perissable',
            field=models.BooleanField(default=False, verbose_name='Produit périssable'),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=80, verbose_name='Numéro de lot')),
                ('date_entree', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée")),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité initiale')),
                ('quantite_restante', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Quantité restante')),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='stock.article')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='stock.depot', verbose_name='Dépôt')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.entreprise')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='stock.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'stock_lot',
                'ordering': ['date_peremption', 'numero_lot'],
            },
        ),
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=120, verbose_name='Numéro de série')),
                ('statut', models.CharField(choices=[('en_stock', 'En stock'), ('vendu', 'Vendu'), ('retire', 'Retiré / SAV')], default='en_stock', max_length=10)),
                ('date_entree', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='stock.article')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros_serie', to='stock.depot', verbose_name='Dépôt')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='core.entreprise')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros_serie', to='stock.lot')),
            ],
            options={
                'verbose_name': 'Numéro de série',
                'verbose_name_plural': 'Numéros de série',
                'db_table': 'stock_numero_serie',
                'ordering': ['article__designation', 'numero_serie'],
            },
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('article', 'numero_lot'), name='unique_lot_par_article'),
        ),
        migrations.AddConstraint(
            model_name='numeroserie',
            constraint=models.UniqueConstraint(fields=('article', 'numero_serie'), name='unique_serie_par_article'),
        ),
    ]
