# Generated by Django 4.2.29 on 2026-07-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_entreprise_type_module_stock'),
        ('stock', '0009_article_gestion_lot_article_gestion_serie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BesoinAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('motif', models.TextField(blank=True, verbose_name='Motif / Justification')),
                ('urgence', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('date_besoin_souhaitee', models.DateField(blank=True, null=True, verbose_name='Besoin pour le')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('traitee', 'Traitée (commande générée)')], default='soumise', max_length=10)),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire du valideur')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_achat_exprimes', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins_achat', to='core.entreprise')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_achat', to='core.service', verbose_name='Service demandeur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besoins_achat_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expression de besoin (achat)',
                'verbose_name_plural': 'Expressions de besoin (achat)',
                'db_table': 'stock_besoin_achat',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DemandeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, verbose_name='Référence')),
                ('date_besoin', models.DateField(default=django.utils.timezone.now, verbose_name='Date du besoin')),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('convertie', 'Convertie en devis')], default='soumise', max_length=10)),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire du valideur')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_vente', to='stock.client')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_vente_creees', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
                ('document_genere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='stock.documentvente', verbose_name='Devis généré')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_vente', to='core.entreprise')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_vente_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expression de besoin (vente)',
                'verbose_name_plural': 'Expressions de besoin (vente)',
                'db_table': 'stock_demande_vente',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='categorie',
            field=models.CharField(choices=[('strategique', 'Stratégique (A)'), ('standard', 'Standard (B)'), ('occasionnel', 'Occasionnel (C)')], default='standard', max_length=12, verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='note_evaluation',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Note d'évaluation (/20)"),
        ),
        migrations.CreateModel(
            name='LigneDemandeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_souhaitee', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité souhaitée')),
                ('prix_indicatif', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prix indicatif (GNF)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_demande_vente', to='stock.article')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.demandevente')),
            ],
            options={
                'verbose_name': 'Ligne de demande de vente',
                'verbose_name_plural': 'Lignes de demande de vente',
                'db_table': 'stock_ligne_demande_vente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LigneBesoinAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantité demandée')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_besoin_achat', to='stock.article')),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.besoinachat')),
                ('ligne_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_besoin_couvertes', to='stock.lignecommande', verbose_name='Ligne de commande générée')),
            ],
            options={
                'verbose_name': "Ligne d'expression de besoin",
                'verbose_name_plural': "Lignes d'expression de besoin",
                'db_table': 'stock_ligne_besoin_achat',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='demandevente',
            constraint=models.UniqueConstraint(fields=('entreprise', 'reference'), name='unique_demande_vente_reference_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='besoinachat',
            constraint=models.UniqueConstraint(fields=('entreprise', 'reference'), name='unique_besoin_achat_reference_par_entreprise'),
        ),
    ]
