# Generated by Django 4.2.29 on 2026-07-15 16:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_besoinachat_demandevente_fournisseur_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='remise_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Remise habituelle (%)'),
        ),
        migrations.AlterField(
            model_name='documentvente',
            name='remise_globale_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Remise globale (%)'),
        ),
        migrations.AlterField(
            model_name='documentvente',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='remise_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Remise (%)'),
        ),
    ]
