# Generated by Django 5.2.1 on 2026-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe_nom', models.CharField(default='Fastlane Logistic', max_length=120, verbose_name='Société')),
                ('activite', models.CharField(default='Transport de Bauxite', max_length=120, verbose_name='Activité principale')),
                ('devise', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('duree_amortissement', models.PositiveIntegerField(default=5, verbose_name="Durée d'amortissement par défaut (années)")),
                ('taux_residuel', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, verbose_name='Valeur résiduelle (fraction du prix)')),
                ('prix_carburant', models.DecimalField(decimal_places=2, default=12000, max_digits=12, verbose_name='Prix moyen carburant (GNF/litre)')),
                ('tarif_bauxite', models.DecimalField(decimal_places=2, default=85000, max_digits=14, verbose_name='Tarif moyen transport bauxite (GNF/tonne)')),
                ('taux_tva', models.DecimalField(decimal_places=4, default=0.18, max_digits=5, verbose_name='Taux TVA')),
                ('jours_ouvres_mois', models.PositiveIntegerField(default=26, verbose_name='Jours ouvrés par mois')),
            ],
            options={
                'verbose_name': 'Paramètre général',
                'verbose_name_plural': 'Paramètres généraux',
            },
        ),
    ]
