# Generated by Django 4.2.29 on 2026-06-09 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_licence_licencelocale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('structure', models.CharField(blank=True, max_length=200, verbose_name='Structure / Organisation')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la visite')),
                ('service_visite', models.CharField(blank=True, max_length=200, verbose_name='Service visité')),
                ('responsable_visite', models.CharField(blank=True, max_length=200, verbose_name='Responsable visité')),
                ('heure_arrivee', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Heure d'arrivée")),
                ('heure_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('badge_numero', models.CharField(blank=True, max_length=30, verbose_name='Numéro de badge')),
                ('observations', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiteurs_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteurs', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'db_table': 'secretariat_visiteur',
                'ordering': ['-heure_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Tâche')),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('urgente', 'Urgente')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('etat', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=10, verbose_name='État')),
                ('rappel', models.BooleanField(default=False, verbose_name='Notification / rappel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_secretariat_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_secretariat', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'db_table': 'secretariat_tache',
                'ordering': ['etat', 'date_limite'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Objet de la réunion')),
                ('date_reunion', models.DateTimeField(verbose_name='Date et heure')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('participants', models.TextField(blank=True, verbose_name='Liste des participants')),
                ('ordre_du_jour', models.TextField(blank=True, verbose_name='Ordre du jour')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('decisions', models.TextField(blank=True, verbose_name='Décisions prises')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'db_table': 'secretariat_reunion',
                'ordering': ['-date_reunion'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_visiteur', models.CharField(max_length=200, verbose_name='Nom du visiteur')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif du rendez-vous')),
                ('personne_concernee', models.CharField(blank=True, max_length=200, verbose_name='Personne concernée')),
                ('date_rdv', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée (minutes)')),
                ('rappel', models.BooleanField(default=True, verbose_name='Rappel automatique')),
                ('rappel_minutes', models.PositiveIntegerField(default=30, verbose_name='Rappel (minutes avant)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('reporte', 'Reporté'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=15)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'secretariat_rendezvous',
                'ordering': ['date_rdv'],
            },
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('categorie', models.CharField(choices=[('lettre', 'Lettre'), ('rapport', 'Rapport'), ('note_service', 'Note de service'), ('contrat', 'Contrat'), ('facture', 'Facture'), ('decision', 'Décision'), ('proces_verbal', 'Procès-verbal'), ('autre', 'Autre')], default='lettre', max_length=20, verbose_name='Catégorie')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu du modèle')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_documents', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'db_table': 'secretariat_modele_document',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('categorie', models.CharField(choices=[('lettre', 'Lettre'), ('rapport', 'Rapport'), ('note_service', 'Note de service'), ('contrat', 'Contrat'), ('facture', 'Facture'), ('decision', 'Décision'), ('proces_verbal', 'Procès-verbal'), ('autre', 'Autre')], default='lettre', max_length=20, verbose_name='Catégorie')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='secretariat/documents/', verbose_name='Fichier (PDF, Word, Excel)')),
                ('description', models.TextField(blank=True)),
                ('date_document', models.DateField(default=django.utils.timezone.now, verbose_name='Date du document')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_secretariat_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_secretariat', to='core.entreprise')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_secretariat_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'secretariat_document',
                'ordering': ['-date_document', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(max_length=30, verbose_name="Numéro d'ordre")),
                ('type_courrier', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant')], default='entrant', max_length=10, verbose_name='Type')),
                ('expediteur', models.CharField(blank=True, max_length=200, verbose_name='Expéditeur')),
                ('destinataire', models.CharField(blank=True, max_length=200, verbose_name='Destinataire')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('date_courrier', models.DateField(default=django.utils.timezone.now, verbose_name='Date de réception / envoi')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='secretariat/courriers/', verbose_name='Scan / pièce jointe')),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_attente', 'En attente'), ('traite', 'Traité'), ('archive', 'Archivé')], default='recu', max_length=15)),
                ('observations', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriers', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'db_table': 'secretariat_courrier',
                'ordering': ['-date_courrier', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact', models.CharField(choices=[('interne', 'Contact interne'), ('client', 'Client'), ('fournisseur', 'Fournisseur'), ('partenaire', 'Partenaire'), ('administration', 'Administration'), ('externe', 'Autre contact externe')], default='externe', max_length=20, verbose_name='Type de contact')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('fonction', models.CharField(blank=True, max_length=200, verbose_name='Fonction')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_secretariat', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'secretariat_contact',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_appel', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant'), ('manque', 'Manqué')], default='entrant', max_length=10, verbose_name="Type d'appel")),
                ('nom_appelant', models.CharField(max_length=200, verbose_name="Nom de l'appelant")),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Numéro de téléphone')),
                ('objet', models.CharField(max_length=255, verbose_name="Objet de l'appel")),
                ('message', models.TextField(blank=True, verbose_name='Message laissé')),
                ('suivi_a_faire', models.BooleanField(default=False, verbose_name='Suivi à faire')),
                ('suivi_effectue', models.BooleanField(default=False, verbose_name='Suivi effectué')),
                ('date_appel', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'appel")),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
                'db_table': 'secretariat_appel',
                'ordering': ['-date_appel'],
            },
        ),
        migrations.CreateModel(
            name='ActionReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Action')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('etat', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=10, verbose_name='État')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='secretariat.reunion')),
            ],
            options={
                'verbose_name': 'Action de réunion',
                'verbose_name_plural': 'Actions de réunion',
                'db_table': 'secretariat_action_reunion',
                'ordering': ['echeance'],
            },
        ),
        migrations.AddConstraint(
            model_name='courrier',
            constraint=models.UniqueConstraint(fields=('entreprise', 'numero_ordre'), name='unique_courrier_numero_par_entreprise'),
        ),
    ]
