# Generated by Django 4.2.29 on 2026-06-27 08:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_travail', '0013_alter_pointage_statut_pointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrageconges',
            name='jours_conges_annuels',
            field=models.DecimalField(decimal_places=1, default=Decimal('30.0'), help_text='Nombre de jours de congés annuels de base (Code du Travail Art. 222 : 30 j/an)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='parametrageconges',
            name='jours_par_mois',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.5'), help_text='Nombre de jours acquis par mois travaillé (Code du Travail Art. 222 : 2,5 j/mois)', max_digits=3),
        ),
    ]
