# Generated by Django 5.2.1 on 2026-04-19 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='ex: AO-2026-001', max_length=50, unique=True, verbose_name='Référence')),
                ('titre', models.CharField(max_length=220, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('objet', models.CharField(help_text='Résumé court affiché dans la liste', max_length=300, verbose_name='Objet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('lieu_execution', models.CharField(blank=True, max_length=200, verbose_name="Lieu d'exécution")),
                ('date_publication', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de publication')),
                ('date_limite', models.DateField(verbose_name='Date limite de dépôt')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone de contact')),
                ('document', models.FileField(blank=True, null=True, upload_to='appels_offres/', verbose_name="Dossier d'appel d'offres (PDF)")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert', 'Ouvert'), ('clos', 'Clos')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Appel d'offres",
                'verbose_name_plural': "Appels d'offres",
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('date_evenement', models.DateField(verbose_name="Date de l'événement")),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('resume', models.CharField(blank=True, help_text="Phrase d'accroche affichée dans la liste", max_length=300, verbose_name='Résumé')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name='Image de couverture')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_evenement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageAPropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='À propos de Fastlane Logistic', max_length=200, verbose_name='Titre')),
                ('presentation', models.TextField(default='Fastlane Logistic est un acteur du transport de bauxite en Guinée, au service des grands opérateurs miniers.', verbose_name='Présentation')),
                ('mission', models.TextField(blank=True, verbose_name='Notre mission')),
                ('vision', models.TextField(blank=True, verbose_name='Notre vision')),
                ('valeurs', models.TextField(blank=True, verbose_name='Nos valeurs')),
                ('chiffres_cles', models.TextField(blank=True, help_text="Ex.:\n50+|Camions\n200|Collaborateurs\n15|Ans d'expérience", verbose_name="Chiffres clés (un par ligne, format 'valeur|libellé')")),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail public')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone public')),
            ],
            options={
                'verbose_name': 'Page « À propos »',
                'verbose_name_plural': 'Page « À propos »',
            },
        ),
    ]
