# Generated by Django 5.2.1 on 2026-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('entreprise', models.CharField(blank=True, max_length=180, verbose_name='Entreprise / Organisation')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('devis', 'Demande de devis'), ('partenariat', 'Proposition de partenariat'), ('recrutement', 'Recrutement / candidature'), ('info', "Demande d'information"), ('reclamation', 'Réclamation'), ('autre', 'Autre')], default='info', max_length=30, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('reponse_interne', models.TextField(blank=True, verbose_name='Note interne / Réponse')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
