# Generated by Django 4.2.7 on 2026-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0133_modele_standard_guineerh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletinpaie",
            name="contribution_onfpp",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="ONFPP 1,5% sur base VF/ONFPP",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpaie",
            name="taxe_apprentissage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="TA 2% sur base VF/ONFPP",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpaie",
            name="versement_forfaitaire",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="VF 6% sur base VF/ONFPP",
                max_digits=15,
            ),
        ),
    ]
