# Generated by Django 5.2.1 on 2026-04-17 10:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Code employé')),
                ('prenom', models.CharField(max_length=80, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom')),
                ('fonction', models.CharField(choices=[('CHAUFFEUR', 'Chauffeur'), ('MECANICIEN', 'Mécanicien'), ('PNEUMATICIEN', 'Pneumaticien'), ('ELECTRICIEN', 'Électricien auto'), ('SOUDEUR', 'Soudeur'), ('SUPERVISEUR', 'Superviseur'), ('AGENT', 'Agent logistique'), ('AIDE', 'Aide mécanicien'), ('ADMIN', 'Administratif'), ('GARDIEN', 'Gardien')], max_length=20, verbose_name='Fonction')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('site_prestation', models.CharField(blank=True, max_length=80, verbose_name='Site de prestation')),
                ('salaire_jour', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire / jour (GNF)')),
                ('salaire_base_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salaire de base mensuel (GNF)')),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Primes mensuelles (GNF)')),
                ('taux_charges', models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5, verbose_name='Taux charges sociales')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='flotte.camion', verbose_name='Camion assigné')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HeureSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure début')),
                ('heure_fin', models.TimeField(verbose_name='Heure fin')),
                ('type_hs', models.CharField(choices=[('OUVRE', 'Jour ouvré'), ('NUIT', 'Nuit'), ('DIMANCHE', 'Dimanche'), ('FERIE', 'Jour férié')], default='OUVRE', max_length=10, verbose_name='Type')),
                ('majoration', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Ex. 0.25 pour +25%, 1.00 pour +100%', max_digits=4, verbose_name='Majoration')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif / Description')),
                ('valide_par', models.CharField(blank=True, max_length=100, verbose_name='Validé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures_sup', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Heure supplémentaire',
                'verbose_name_plural': 'Heures supplémentaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('code', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('C', 'Congé'), ('M', 'Maladie'), ('D', 'Dimanche travaillé'), ('R', 'Repos / Jour férié')], default='P', max_length=2, verbose_name='Code')),
                ('commentaire', models.CharField(blank=True, max_length=200, verbose_name='Commentaire')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Pointage (Attendance)',
                'verbose_name_plural': 'Pointages (Attendance)',
                'ordering': ['-date', 'employe__code'],
                'indexes': [models.Index(fields=['date', 'employe'], name='rh_attendan_date_d5aee5_idx')],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
