# Generated by Django 5.2.1 on 2026-04-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotte', '0001_initial'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_depense', models.CharField(choices=[('IMMAT', 'Immatriculation'), ('ASSU', 'Assurance'), ('VT', 'Visite technique'), ('TAXE', 'Taxe de transport'), ('LICENCE', 'Licence'), ('BANQUE', 'Frais bancaires'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Type de dépense')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Référence / N° document')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant (GNF)')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('statut', models.CharField(choices=[('PAYE', 'Payé'), ('ATTENTE', 'En attente'), ('RETARD', 'En retard')], default='PAYE', max_length=10, verbose_name='Statut')),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_admin', to='flotte.camion')),
            ],
            options={
                'verbose_name': 'Dépense administrative',
                'verbose_name_plural': 'Dépenses administratives',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_panne', models.CharField(choices=[('PNEUS', 'Pneus'), ('MOTEUR', 'Moteur'), ('FREINAGE', 'Freinage'), ('TRANSMISSION', 'Transmission'), ('SUSPENSION', 'Suspension'), ('ELECTRICITE', 'Électricité'), ('HYDRAULIQUE', 'Hydraulique'), ('CARROSSERIE', 'Carrosserie'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type')),
                ('piece_remplacee', models.CharField(blank=True, max_length=200, verbose_name='Pièce remplacée')),
                ('fournisseur', models.CharField(blank=True, max_length=120, verbose_name='Fournisseur / Garage')),
                ('cout_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût pièces (GNF)')),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Coût main d'œuvre (GNF)")),
                ('duree_immobilisation', models.PositiveIntegerField(default=0, verbose_name='Durée immobilisation (jours)')),
                ('observations', models.CharField(blank=True, max_length=200, verbose_name='Observations')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pannes', to='flotte.camion')),
            ],
            options={
                'verbose_name': 'Panne / Réparation',
                'verbose_name_plural': 'Pannes & réparations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('prenom', models.CharField(max_length=80, verbose_name='First Name / Prénom')),
                ('nom', models.CharField(max_length=80, verbose_name='Last Name / Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('plaque', models.CharField(max_length=30, verbose_name='Plate / Plaque')),
                ('carte_entree', models.CharField(blank=True, max_length=40, verbose_name="Carte d'entrée / Entry car N°")),
                ('lieu_chargement', models.CharField(max_length=120, verbose_name='Lieu de chargement / Loading zone')),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ / Departure Time')),
                ('heure_pesee_start', models.TimeField(blank=True, null=True, verbose_name='Heure pesée Start')),
                ('heure_pesee_end', models.TimeField(blank=True, null=True, verbose_name='Heure pesée End')),
                ('observation', models.CharField(blank=True, max_length=200, verbose_name='Observation')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantité / Quantity (T)')),
                ('num_bon', models.CharField(max_length=40, unique=True, verbose_name='N° Bon')),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons', to='flotte.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Bon de transport',
                'verbose_name_plural': 'Bons de transport',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'plaque'], name='operations__date_fb5039_idx')],
            },
        ),
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(blank=True, null=True, verbose_name='Heure')),
                ('km_tableau_bord', models.PositiveIntegerField(default=0, verbose_name='Km au tableau de bord')),
                ('km_avant', models.PositiveIntegerField(default=0, verbose_name='Km avant prise')),
                ('litres_avant', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Nb L avant')),
                ('litres_apres', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Nb L après')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (GNF/L)')),
                ('station', models.CharField(blank=True, max_length=120, verbose_name='Station / Lieu')),
                ('observations', models.CharField(blank=True, max_length=200, verbose_name='Observations')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carburants', to='flotte.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carburants', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Prise de carburant',
                'verbose_name_plural': 'Carburant — Suivi des prises',
                'ordering': ['-date', '-heure'],
                'indexes': [models.Index(fields=['date', 'camion'], name='operations__date_2a17c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransportBauxite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('trajet', models.CharField(max_length=200, verbose_name='Trajet (départ → arrivée)')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Distance (km)')),
                ('tonnage', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tonnage transporté (T)')),
                ('tarif_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tarif (GNF/T)')),
                ('client', models.CharField(default='CBG', max_length=80, verbose_name='Client (société minière)')),
                ('num_bon', models.CharField(blank=True, max_length=40, verbose_name='N° Bon de livraison')),
                ('observations', models.CharField(blank=True, max_length=200, verbose_name='Observations')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='flotte.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Voyage bauxite',
                'verbose_name_plural': 'Transport bauxite',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'camion'], name='operations__date_27342c_idx'), models.Index(fields=['client'], name='operations__client_48b6db_idx')],
            },
        ),
    ]
