# Generated by Django 5.2.1 on 2026-04-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontransport',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Contrat client auquel ce bon de transport est rattaché.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons', to='facturation.contrat', verbose_name='Projet / Contrat'),
        ),
        migrations.AddField(
            model_name='carburant',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, ce carburant sera imputé à ce contrat. Sinon, il sera réparti au prorata entre tous les contrats actifs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carburants', to='facturation.contrat', verbose_name='Projet / Contrat'),
        ),
        migrations.AddField(
            model_name='depenseadmin',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, cette dépense sera imputée à ce contrat. Sinon, elle sera répartie au prorata entre tous les contrats actifs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_admin', to='facturation.contrat', verbose_name='Projet / Contrat'),
        ),
        migrations.AddField(
            model_name='panne',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, cette panne sera imputée à ce contrat. Sinon, elle sera répartie au prorata entre tous les contrats actifs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes', to='facturation.contrat', verbose_name='Projet / Contrat'),
        ),
        migrations.AddField(
            model_name='transportbauxite',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Contrat client auquel ce voyage est rattaché. Détermine la facturation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='facturation.contrat', verbose_name='Projet / Contrat'),
        ),
    ]
