# Generated by Django 5.2.1 on 2026-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_bontransport_contrat_carburant_contrat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankBonCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro émis')),
            ],
            options={
                'verbose_name': 'Compteur bons vierges',
                'verbose_name_plural': 'Compteur bons vierges',
            },
        ),
    ]
