# Generated by Django 5.2.1 on 2026-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_fichecarburant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontransport',
            name='heure_observation_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Observation H fin'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='heure_observation_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Observation H debut'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='quantite_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantite 1'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='quantite_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantite 2'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='quantite_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantite 3'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='quantite_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantite 4'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='remarque',
            field=models.CharField(blank=True, max_length=200, verbose_name='Remarque'),
        ),
    ]
