# Generated by Django 5.2.1 on 2026-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_backfill_bontransport_quantite_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='chauffeur_nom',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nom du chauffeur'),
        ),
        migrations.AddField(
            model_name='panne',
            name='contact_fournisseur',
            field=models.CharField(blank=True, max_length=80, verbose_name='Contact fournisseur'),
        ),
        migrations.AddField(
            model_name='panne',
            name='date_commande',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la commande'),
        ),
        migrations.AddField(
            model_name='panne',
            name='date_reception_commande',
            field=models.DateField(blank=True, null=True, verbose_name='Date de reception de la commande'),
        ),
        migrations.AddField(
            model_name='panne',
            name='description_panne',
            field=models.TextField(blank=True, verbose_name='Description de la panne'),
        ),
        migrations.AddField(
            model_name='panne',
            name='nom_technicien',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nom du technicien'),
        ),
        migrations.AddField(
            model_name='panne',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='panne',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantite'),
        ),
        migrations.AddField(
            model_name='panne',
            name='reference_piece',
            field=models.CharField(blank=True, max_length=120, verbose_name='Reference de la piece remplacee'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='type_panne',
            field=models.CharField(choices=[('PNEUS', 'Pneus'), ('MOTEUR', 'Moteur'), ('FREINAGE', 'Freinage'), ('TRANSMISSION', 'Transmission'), ('SUSPENSION', 'Suspension'), ('ELECTRICITE', 'Électricité'), ('HYDRAULIQUE', 'Hydraulique'), ('CARROSSERIE', 'Carrosserie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type'),
        ),
    ]
