# Generated by Django 4.2.29 on 2026-07-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_alter_droitacces_module'),
        ('comptabilite', '0012_ecriturecomptable_idx_ecriture_journal_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numéro')),
                ('type_bordereau', models.CharField(choices=[('versement', 'Bordereau de versement (espèces)'), ('cheques', 'Bordereau de remise de chèques')], max_length=10, verbose_name='Type')),
                ('date_remise', models.DateField(default=django.utils.timezone.now, verbose_name='Date de remise')),
                ('deposant', models.CharField(blank=True, max_length=200, verbose_name='Déposant')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptebancaire', verbose_name='Compte bancaire crédité')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordereaux_remise', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Bordereau de remise',
                'verbose_name_plural': 'Bordereaux de remise',
                'db_table': 'bordereaux_remise',
                'ordering': ['-date_remise', '-id'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='LigneBordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description / N° chèque')),
                ('banque_emettrice', models.CharField(blank=True, max_length=100, verbose_name='Banque émettrice')),
                ('tireur', models.CharField(blank=True, max_length=200, verbose_name='Tireur / Origine')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.bordereauremise')),
            ],
            options={
                'verbose_name': 'Ligne de bordereau',
                'verbose_name_plural': 'Lignes de bordereau',
                'db_table': 'lignes_bordereau',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name="Libellé de l'emprunt")),
                ('preteur', models.CharField(max_length=200, verbose_name='Prêteur / Banque')),
                ('reference_contrat', models.CharField(blank=True, max_length=100, verbose_name='Référence du contrat')),
                ('capital_emprunte', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Capital emprunté (GNF)')),
                ('taux_annuel', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Taux annuel (%)')),
                ('nombre_echeances', models.PositiveIntegerField(verbose_name="Nombre d'échéances")),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=15)),
                ('date_deblocage', models.DateField(verbose_name='Date de déblocage des fonds')),
                ('date_premiere_echeance', models.DateField(verbose_name='Date de la première échéance')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé'), ('contentieux', 'Contentieux')], default='en_cours', max_length=15)),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'db_table': 'emprunts',
                'ordering': ['-date_deblocage'],
            },
        ),
        migrations.CreateModel(
            name='PieceCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numéro de pièce')),
                ('type_piece', models.CharField(choices=[('entree', 'Entrée de caisse'), ('sortie', 'Sortie de caisse')], max_length=10, verbose_name='Type')),
                ('date_operation', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('libelle', models.CharField(max_length=255, verbose_name='Motif / Libellé')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire / Verseur (si tiers non référencé)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (facture, contrat…)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.ecriturecomptable', verbose_name='Écriture liée')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_caisse', to='core.entreprise')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.tiers', verbose_name='Tiers (payé à / reçu de)')),
            ],
            options={
                'verbose_name': 'Pièce de caisse',
                'verbose_name_plural': 'Pièces de caisse',
                'db_table': 'pieces_caisse',
                'ordering': ['-date_operation', '-id'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
    ]
