# Generated by Django 4.2.29 on 2026-07-03 11:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_alter_droitacces_module'),
        ('comptabilite', '0013_bordereauremise_lignebordereau_emprunt_piececaisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereauremise',
            name='type_bordereau',
            field=models.CharField(choices=[('versement', 'Bordereau de versement (espèces)'), ('cheques', 'Bordereau de remise de chèques'), ('retrait', 'Bordereau de retrait')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('achat', "Facture d'achat"), ('vente', 'Facture de vente'), ('avoir_client', "Facture d'avoir (client)"), ('avoir_fournisseur', "Facture d'avoir (fournisseur)"), ('acompte', "Facture d'acompte")], max_length=20),
        ),
        migrations.CreateModel(
            name='ArreteCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numéro')),
                ('date_arrete', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'arrêté")),
                ('nb_20000', models.PositiveIntegerField(default=0, verbose_name='Billets de 20 000')),
                ('nb_10000', models.PositiveIntegerField(default=0, verbose_name='Billets de 10 000')),
                ('nb_5000', models.PositiveIntegerField(default=0, verbose_name='Billets de 5 000')),
                ('nb_2000', models.PositiveIntegerField(default=0, verbose_name='Billets de 2 000')),
                ('nb_1000', models.PositiveIntegerField(default=0, verbose_name='Billets de 1 000')),
                ('nb_500', models.PositiveIntegerField(default=0, verbose_name='Billets de 500')),
                ('autres_valeurs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Autres valeurs (pièces, etc.)')),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Solde théorique (livre de caisse)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation / justification des écarts')),
                ('caissier', models.CharField(blank=True, max_length=200, verbose_name='Caissier')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arretes_caisse', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Arrêté de caisse',
                'verbose_name_plural': 'Arrêtés de caisse',
                'db_table': 'arretes_caisse',
                'ordering': ['-date_arrete', '-id'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
    ]
