# Generated by Django 4.2.29 on 2026-07-03 15:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_alter_droitacces_module'),
        ('comptabilite', '0014_alter_bordereauremise_type_bordereau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationPatente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name="Année d'imposition")),
                ('activite', models.CharField(max_length=255, verbose_name='Activité exercée')),
                ('reference_tarif', models.CharField(blank=True, max_length=100, verbose_name='Classe / référence du tarif des patentes')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name="Chiffre d'affaires (GNF)")),
                ('valeur_locative', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Valeur locative des locaux (GNF)')),
                ('droit_fixe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Droit fixe (GNF)')),
                ('taux_proportionnel', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='Taux du droit proportionnel (%)')),
                ('droit_proportionnel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Droit proportionnel (GNF)')),
                ('date_declaration', models.DateField(default=django.utils.timezone.now, verbose_name='Date de déclaration')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('deposee', 'Déposée'), ('payee', 'Payée')], default='brouillon', max_length=10)),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_patente', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Déclaration de patente',
                'verbose_name_plural': 'Déclarations de patente',
                'db_table': 'declarations_patente',
                'ordering': ['-annee', '-date_declaration'],
                'unique_together': {('entreprise', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ChequeEmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=30, verbose_name='N° de chèque')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name='Bénéficiaire (ordre de)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('lieu_emission', models.CharField(default='Conakry', max_length=100, verbose_name="Lieu d'émission")),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif / Référence')),
                ('barre', models.BooleanField(default=True, verbose_name='Chèque barré (non endossable)')),
                ('statut', models.CharField(choices=[('emis', 'Émis'), ('encaisse', 'Encaissé'), ('annule', 'Annulé'), ('oppose', 'Opposition')], default='emis', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptebancaire', verbose_name='Compte bancaire tiré')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques_emis', to='core.entreprise')),
            ],
            options={
                'verbose_name': 'Chèque émis',
                'verbose_name_plural': 'Chèques émis',
                'db_table': 'cheques_emis',
                'ordering': ['-date_emission', '-id'],
                'unique_together': {('entreprise', 'compte_bancaire', 'numero_cheque')},
            },
        ),
    ]
