# Generated by Django 4.2.29 on 2026-07-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_droitacces_module'),
        ('comptabilite', '0015_declarationpatente_chequeemis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecriturecomptable',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='ecritures/pieces/', verbose_name='Pièce justificative (PDF, scan, photo…)'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='centre_analyse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecritures', to='comptabilite.centreanalyse', verbose_name='Dimension analytique (projet, agence, centre de coût…)'),
        ),
        migrations.CreateModel(
            name='RegleEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(help_text='vente, achat, encaissement_client, paiement_fournisseur, entree_caisse, sortie_caisse, salaire, achat_immobilisation…', max_length=30, verbose_name='Code opération')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre de la ligne')),
                ('sens', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=6)),
                ('role_compte', models.CharField(choices=[('fixe', 'Compte fixe (numéro ci-dessous)'), ('tiers', 'Compte auxiliaire du tiers'), ('tresorerie', 'Banque ou Caisse selon le mode de paiement')], default='fixe', max_length=12)),
                ('compte_numero', models.CharField(blank=True, max_length=20, verbose_name='N° de compte (si compte fixe)')),
                ('compte_intitule', models.CharField(blank=True, max_length=200, verbose_name='Intitulé (création auto du compte)')),
                ('base_montant', models.CharField(choices=[('ht', 'Montant HT'), ('tva', 'Montant TVA'), ('ttc', 'Montant TTC')], default='ttc', max_length=5, verbose_name='Montant appliqué')),
                ('ignorer_si_nul', models.BooleanField(default=True, verbose_name='Ignorer la ligne si le montant est nul')),
                ('journal_type', models.CharField(blank=True, max_length=2, verbose_name='Journal (vide = journal du schéma)')),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, help_text='Vide = règle globale (toutes les entreprises)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_ecriture', to='core.entreprise')),
            ],
            options={
                'verbose_name': "Règle d'écriture",
                'verbose_name_plural': "Règles d'écriture",
                'db_table': 'regles_ecriture',
                'ordering': ['operation', 'ordre'],
            },
        ),
    ]
