# Generated by Django 4.2.29 on 2026-07-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0018_seed_plan_syscohada_etendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedeclarationtva',
            name='sens',
            field=models.CharField(choices=[('COLLECTEE', 'TVA collectée (ventes)'), ('DEDUCTIBLE', 'TVA déductible (achats)')], default='COLLECTEE', help_text='Collectée sur les ventes ou déductible sur les achats', max_length=12, verbose_name='Sens de la TVA'),
        ),
    ]
