# -*- coding: utf-8 -*-
"""
Initialise le plan comptable SYSCOHADA (comptes essentiels, classes 1 à 8)
pour une ou toutes les entreprises. Idempotent : les comptes existants ne
sont jamais modifiés.

Usage :
    python manage.py seed_plan_syscohada            # toutes les entreprises
    python manage.py seed_plan_syscohada --entreprise <uuid>
"""
from django.core.management.base import BaseCommand

from core.models import Entreprise
from comptabilite.models import PlanComptable

# Plan SYSCOHADA révisé étendu pour PME/ETI.
PLAN_SYSCOHADA = [
    # Classe 1 — Ressources durables
    ('1011', 'Capital souscrit, non appelé'),
    ('1012', 'Capital souscrit, appelé, non versé'),
    ('1013', 'Capital souscrit, appelé, versé'),
    ('1061', 'Réserve légale'),
    ('1181', 'Réserves facultatives'),
    ('1210', 'Report à nouveau créditeur'),
    ('1290', 'Report à nouveau débiteur'),
    ('1310', 'Résultat net : bénéfice'),
    ('1390', 'Résultat net : perte'),
    ('1410', 'Subventions d\'équipement'),
    ('1510', 'Provisions réglementées'),
    ('1520', 'Amortissements dérogatoires'),
    ('1610', 'Emprunts obligataires'),
    ('1621', 'Emprunts auprès des établissements de crédit'),
    ('1630', 'Emprunts et dettes assortis de conditions particulières'),
    ('1640', 'Avances reçues et comptes courants bloqués'),
    ('1661', 'Intérêts courus sur emprunts'),
    ('1670', 'Dettes de location-acquisition'),
    ('1680', 'Autres emprunts et dettes'),
    ('1810', 'Dettes liées à des participations'),
    ('1820', 'Comptes permanents bloqués des établissements et succursales'),
    ('1830', 'Comptes de liaison entre établissements'),
    ('1840', 'Comptes de liaison charges et produits'),
    ('1850', 'Comptes permanents non bloqués'),
    ('1910', 'Provisions pour litiges'),
    ('1940', 'Provisions pour pertes de change'),
    ('1980', 'Autres provisions financières pour risques et charges'),
    # Classe 2 — Actif immobilisé
    ('2011', 'Frais d\'établissement'),
    ('2021', 'Charges à répartir sur plusieurs exercices'),
    ('2031', 'Primes de remboursement des obligations'),
    ('2111', 'Frais de développement'),
    ('2121', 'Brevets, licences, concessions et droits similaires'),
    ('2131', 'Logiciels'),
    ('2141', 'Marques'),
    ('2151', 'Fonds commercial'),
    ('2181', 'Autres droits et valeurs incorporels'),
    ('2211', 'Terrains'),
    ('2221', 'Terrains agricoles et forestiers'),
    ('2231', 'Terrains bâtis'),
    ('2241', 'Travaux de mise en valeur des terrains'),
    ('2311', 'Bâtiments industriels et commerciaux'),
    ('2321', 'Bâtiments administratifs'),
    ('2331', 'Ouvrages d\'infrastructure'),
    ('2351', 'Installations générales'),
    ('2411', 'Matériel et outillage industriel'),
    ('2441', 'Matériel et outillage'),
    ('2442', 'Matériel informatique'),
    ('2444', 'Mobilier de bureau'),
    ('2451', 'Matériel de transport'),
    ('2811', 'Amortissements des frais de développement'),
    ('2821', 'Amortissements des brevets, licences et logiciels'),
    ('2831', 'Amortissements des bâtiments'),
    ('2841', 'Amortissements du matériel'),
    ('2844', 'Amortissements du mobilier'),
    ('2845', 'Amortissements du matériel de transport'),
    ('2911', 'Dépréciations des immobilisations incorporelles'),
    ('2921', 'Dépréciations des terrains'),
    ('2931', 'Dépréciations des bâtiments'),
    ('2941', 'Dépréciations du matériel'),
    # Classe 3 — Stocks
    ('3111', 'Marchandises A'),
    ('3121', 'Marchandises B'),
    ('3211', 'Matières premières'),
    ('3221', 'Matières consommables'),
    ('3311', 'Produits en cours'),
    ('3411', 'Produits intermédiaires'),
    ('3511', 'Produits résiduels'),
    ('3611', 'Produits finis'),
    ('3711', 'Produits intermédiaires et finis hors activité ordinaire'),
    ('3811', 'Stocks en cours de route, en consignation ou en dépôt'),
    ('3911', 'Dépréciations des stocks de marchandises'),
    ('3921', 'Dépréciations des stocks de matières premières'),
    ('3931', 'Dépréciations des en-cours de production'),
    ('3961', 'Dépréciations des stocks de produits finis'),
    # Classe 4 — Tiers
    ('4011', 'Fournisseurs'),
    ('4021', 'Fournisseurs, effets à payer'),
    ('4041', 'Fournisseurs d\'immobilisations'),
    ('4081', 'Fournisseurs, factures non parvenues'),
    ('4091', 'Fournisseurs, avances et acomptes versés'),
    ('4111', 'Clients'),
    ('4121', 'Clients, effets à recevoir'),
    ('4141', 'Créances sur cessions d\'immobilisations'),
    ('4161', 'Clients douteux ou litigieux'),
    ('4181', 'Clients, factures à établir'),
    ('4191', 'Clients, avances et acomptes reçus'),
    ('4211', 'Personnel, avances et acomptes'),
    ('4221', 'Personnel, rémunérations dues'),
    ('4231', 'Personnel, oppositions et saisies-arrêts'),
    ('4241', 'Personnel, œuvres sociales internes'),
    ('4281', 'Personnel, charges à payer'),
    ('4311', 'CNSS, cotisations sociales'),
    ('4331', 'Autres organismes sociaux'),
    ('4381', 'Organismes sociaux, charges à payer'),
    ('4411', 'État, impôt sur les bénéfices'),
    ('4421', 'Impôts et taxes d\'État (RTS)'),
    ('4431', 'TVA facturée sur ventes'),
    ('4441', 'État, TVA due'),
    ('4449', 'État, crédit de TVA à reporter'),
    ('4452', 'TVA récupérable sur achats'),
    ('4453', 'TVA récupérable sur immobilisations'),
    ('4454', 'TVA récupérable sur services extérieurs'),
    ('4461', 'État, autres taxes sur le chiffre d\'affaires'),
    ('4471', 'État, impôts retenus à la source'),
    ('4491', 'État, avances et acomptes versés sur impôts'),
    ('4511', 'Groupe, opérations courantes'),
    ('4521', 'Associés, comptes courants'),
    ('4581', 'Associés, opérations faites en commun'),
    ('4611', 'Débiteurs divers'),
    ('4621', 'Créditeurs divers'),
    ('4651', 'Créances sur cessions d\'immobilisations'),
    ('4661', 'Dettes sur acquisitions d\'immobilisations'),
    ('4711', 'Débiteurs divers'),
    ('4712', 'Créditeurs divers'),
    ('4751', 'Créances et dettes sur travaux non encore facturables'),
    ('4761', 'Charges constatées d\'avance'),
    ('4771', 'Produits constatés d\'avance'),
    ('4781', 'Écarts de conversion actif'),
    ('4791', 'Écarts de conversion passif'),
    ('4812', 'Fournisseurs d\'investissements'),
    # Classe 5 — Trésorerie
    ('5011', 'Titres du Trésor et bons de caisse à court terme'),
    ('5021', 'Actions'),
    ('5031', 'Obligations'),
    ('5111', 'Effets à encaisser'),
    ('5121', 'Effets à l\'encaissement'),
    ('5131', 'Chèques à encaisser'),
    ('5141', 'Chèques à l\'encaissement'),
    ('5211', 'Banque'),
    ('5221', 'Banques, autres comptes'),
    ('5231', 'Banques, intérêts courus'),
    ('5311', 'Chèques postaux'),
    ('5411', 'Établissements financiers et assimilés'),
    ('5511', 'Cartes de crédit à encaisser'),
    ('5611', 'Banques, crédits de trésorerie'),
    ('5641', 'Escompte de crédits ordinaires'),
    ('5651', 'Escompte de crédits de campagne'),
    ('5711', 'Caisse'),
    ('5811', 'Régies d\'avances'),
    ('5821', 'Accréditifs'),
    ('5851', 'Virements de fonds'),
    ('5901', 'Dépréciations des titres de placement'),
    # Classe 6 — Charges
    ('6011', 'Achats de marchandises'),
    ('6021', 'Achats de matières premières'),
    ('6022', 'Achats de matières consommables'),
    ('6031', 'Variations des stocks de marchandises'),
    ('6032', 'Variations des stocks de matières premières'),
    ('6033', 'Variations des autres approvisionnements'),
    ('6051', 'Fournitures non stockables — eau'),
    ('6052', 'Fournitures non stockables — électricité'),
    ('6055', 'Fournitures de bureau'),
    ('6041', 'Achats stockés de matières et fournitures consommables'),
    ('6081', 'Achats d\'emballages'),
    ('6111', 'Transports sur achats'),
    ('6121', 'Transports sur ventes'),
    ('6131', 'Transports pour le compte de tiers'),
    ('6141', 'Transports du personnel'),
    ('6181', 'Autres frais de transport'),
    ('6211', 'Sous-traitance générale'),
    ('6221', 'Locations et charges locatives'),
    ('6231', 'Redevances de crédit-bail'),
    ('6241', 'Entretien, réparations et maintenance'),
    ('6251', 'Primes d\'assurance'),
    ('6261', 'Études, recherches et documentation'),
    ('6265', 'Frais de télécommunications'),
    ('6271', 'Frais bancaires'),
    ('6281', 'Frais divers'),
    ('6321', 'Rémunérations d\'intermédiaires et de conseils'),
    ('6331', 'Publicité, publications, relations publiques'),
    ('6341', 'Frais postaux'),
    ('6351', 'Cotisations'),
    ('6371', 'Rémunérations du personnel extérieur'),
    ('6381', 'Autres charges externes'),
    ('6311', 'Impôts et taxes directs (patente)'),
    ('6411', 'Impôts et taxes indirects'),
    ('6451', 'Impôts et taxes sur rémunérations'),
    ('6461', 'Droits d\'enregistrement'),
    ('6471', 'Pénalités et amendes fiscales'),
    ('6511', 'Pertes sur créances clients'),
    ('6541', 'Valeurs comptables des cessions courantes d\'immobilisations'),
    ('6588', 'Autres charges diverses'),
    ('6611', 'Appointements et salaires'),
    ('6621', 'Congés payés'),
    ('6631', 'Primes et gratifications'),
    ('6641', 'Charges sociales (CNSS employeur)'),
    ('6651', 'Indemnités et avantages divers'),
    ('6681', 'Autres charges de personnel'),
    ('6711', 'Intérêts des emprunts'),
    ('6721', 'Intérêts dans loyers de location-acquisition'),
    ('6761', 'Pertes de change financières'),
    ('6771', 'Escomptes accordés'),
    ('6781', 'Autres charges financières'),
    ('6811', 'Dotations aux amortissements d\'exploitation'),
    ('6871', 'Dotations aux amortissements financières'),
    ('6911', 'Dotations aux provisions d\'exploitation'),
    ('6971', 'Dotations aux provisions financières'),
    # Classe 7 — Produits
    ('7011', 'Ventes de marchandises'),
    ('7021', 'Ventes de produits finis'),
    ('7031', 'Ventes de produits intermédiaires'),
    ('7041', 'Travaux facturés'),
    ('7051', 'Études et prestations de services'),
    ('7061', 'Services vendus'),
    ('7071', 'Produits accessoires'),
    ('7078', 'Autres produits accessoires'),
    ('7081', 'Produits des activités annexes'),
    ('7111', 'Production immobilisée incorporelle'),
    ('7211', 'Production immobilisée corporelle'),
    ('7311', 'Variations des stocks de produits finis'),
    ('7321', 'Variations des stocks de produits intermédiaires'),
    ('7331', 'Variations des en-cours de production'),
    ('7411', 'Subventions d\'exploitation'),
    ('7521', 'Quote-part de subventions d\'investissement virée au résultat'),
    ('7541', 'Produits des cessions courantes d\'immobilisations'),
    ('7588', 'Autres produits divers'),
    ('7611', 'Revenus des titres de participation'),
    ('7661', 'Gains de change financiers'),
    ('7671', 'Escomptes obtenus'),
    ('7711', 'Intérêts de prêts'),
    ('7781', 'Autres produits financiers'),
    ('7811', 'Reprises d\'amortissements'),
    ('7871', 'Reprises financières'),
    ('7911', 'Reprises de provisions d\'exploitation'),
    ('7971', 'Reprises de provisions financières'),
    # Classe 8 — Autres charges et produits
    ('8111', 'Valeurs comptables des cessions d\'immobilisations'),
    ('8121', 'Charges hors activités ordinaires'),
    ('8181', 'Autres charges HAO'),
    ('8211', 'Produits des cessions d\'immobilisations'),
    ('8221', 'Produits hors activités ordinaires'),
    ('8281', 'Autres produits HAO'),
    ('8311', 'Charges HAO constatées'),
    ('8411', 'Produits HAO constatés'),
    ('8511', 'Dotations HAO'),
    ('8611', 'Reprises HAO'),
    ('8911', 'Impôts sur le résultat'),
    ('9011', 'Comptes réfléchis'),
    ('9211', 'Centres d\'analyse principaux'),
    ('9221', 'Centres d\'analyse auxiliaires'),
    ('9311', 'Coûts d\'achat'),
    ('9321', 'Coûts de production'),
    ('9331', 'Coûts de distribution'),
    ('9411', 'Stocks analytiques'),
    ('9511', 'Écarts sur coûts préétablis'),
    ('9611', 'Différences d\'incorporation'),
    ('9711', 'Résultats analytiques'),
]


class Command(BaseCommand):
    help = 'Initialise le plan comptable SYSCOHADA étendu — idempotent.'

    def add_arguments(self, parser):
        parser.add_argument('--entreprise', help='UUID d\'une entreprise précise (défaut : toutes)')

    def handle(self, *args, **options):
        entreprises = Entreprise.objects.filter(actif=True)
        if options.get('entreprise'):
            entreprises = entreprises.filter(pk=options['entreprise'])
        for entreprise in entreprises:
            crees = 0
            for numero, intitule in PLAN_SYSCOHADA:
                _, cree = PlanComptable.objects.get_or_create(
                    entreprise=entreprise, numero_compte=numero,
                    defaults={'intitule': intitule, 'classe': numero[0], 'est_actif': True})
                if cree:
                    crees += 1
            self.stdout.write(self.style.SUCCESS(
                f'{entreprise.nom_entreprise} : {crees} compte(s) créé(s), '
                f'{len(PLAN_SYSCOHADA) - crees} déjà présent(s).'))
