# Generated by Django 4.2.29 on 2026-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_licence_licencelocale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='type_module',
            field=models.CharField(choices=[('rh', 'Ressources Humaines'), ('compta', 'Comptabilité'), ('secretariat', 'Secrétariat'), ('both', 'RH + Comptabilité'), ('all', 'RH + Comptabilité + Secrétariat')], default='rh', max_length=20, verbose_name='Type de compte'),
        ),
    ]
