# Generated by Django 4.2.29 on 2026-07-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entreprise_type_module_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droitacces',
            name='module',
            field=models.CharField(choices=[('employes', 'Employés'), ('paie', 'Paie'), ('temps_travail', 'Temps de travail'), ('conges', 'Congés'), ('formation', 'Formation'), ('recrutement', 'Recrutement'), ('comptabilite', 'Comptabilité'), ('dashboard', 'Tableau de bord'), ('rapports', 'Rapports'), ('parametres', 'Paramètres')], max_length=50),
        ),
    ]
